### ISSUE TITLE
CCM interpretation

### ISSUE THREAD

**Issue by nsankar** [PengTao-HUST/crossmapy#1]
@PengTao-HUST  Thanks for developing this excellent library. I have a few questions.

1. In the CCM , do you compute the bi-variate cause and effect ? for example, In the air-pollution example , how do we choose the cause and effect  variable ?  or it is computed bi-directionally for the timeseries. for example NO2 --> RSP and then RSP ---> NO2 in the airpollution example ?
    
2. How do we interpret the following causal scores from the heatmap chart? for instance, RSP to NO2 is .605 , which is the cause here and which is the effect ?
![image](https://user-images.githubusercontent.com/431890/170722851-41e87afe-b3ba-4db7-8cab-cf6a845d271b.png)

3. What is the min and max for the scores? 0 to1 or -1 to 1 ?
Thanks in advance.

**Comment by PengTao-HUST** [comment]
Thanks for your comments. Here are my answers:

1.  For all algorithms in this package, causal strength is computed bi-directionally, i.e., all possible causalities are considered for all variables of the time series. 
2. The label of x(y)-axis of the heatmap stands for the cause (effect) variable. Thus, in the case of "RSP to NO2 is 0.605", NO2 is cause and RSP is effect. 
3. In this package, the calculated causal scores of all algorithms are normalized between 0 and 1, except GC and TE, which are 0 to infinity.

I hope above answers are helpful to you!

**Comment by nsankar** [comment]
@PengTao-HUST  thank you for clarifying.
